### ISSUE TITLE
GoLang

### ISSUE THREAD

**Issue by hydra-yse** [gSpera/ex-manager#2]
I don't think Go is the right choice for this project, especially when paired with React. I suggest you change your stack to **raw SQL Syntax** for the backend (made in **Microsoft Access**) paired with **vanilla HTML and CSS** for best performance. I hope you will implement my suggestions if you intend to earn some ⭐.

**Comment by gSpera** [comment]
For you to know, the language is called Go, not Golang
Also Microsoft Access is for rich, i don't a quarter of dollar.
Vanilla HTML and CSS like your Vue/Node/Javascript/V8/Chrome/Electron application??
I want all the cycles of cpus for me.
Count the star in the universe, when you will finish, then remove yours.
